remote: &remote
  host: "https://energy.example.com/"
  api_key: '1234567890'
sentry_dsn: 'https://public:secret@example.com/project-id'
sources:
  - type: "d0"
    path: "/dev/ttyUSB5"
    uploads:
      1.8.0:
        <<: *remote
        serial: "ABC123"
    mqtt_publishes:
      1.8.0:
        url: mqtt://10.13.37.10
        topic: "meters/ABC123/total_energy"
  - type: "modbus"
    url: "modbus://127.0.0.1:502"
    unit_id: 128
    registers:
      totalWH:
        address: 40302
        register_count: 4
        unit: 'Wh'
  - type: "modbus"
    path: "/dev/ttyUSB0"
    baud: 4800
    unit_id: 128
    registers:
      totalWH:
        type: input
        address: 30073
        register_count: 2
        format: float
        unit: 'kWh'
  - type: "fritz"
    url: "http://192.168.178.1"
    username: "user"
    password: "123456"
    # Leaving switches out will try to enumerate all switches
    # Though this takes longer than using a predefined list
    switches:
      refrigerator: "012340000123"
  - type: "vzlogger"
    url: "http://localhost:8081/"
    channels:
      - name: net-input
        uuid: "f8614830-2d2a-4027-8b8b-ede467ae1f45"
        unit: "Wh"
  - type: "shelly1"
    url: "http://192.168.33.1"
    username: "user"
    password: "123456"
    # meters are referred to by their index (0 on one channel devices, 0-2 on three channel, etc.)
    meters:
      desk: 0
