remote: &remote
  host: "https://energy.example.com/"
  api_key: '1234567890'
sentry_dsn: 'https://public:secret@example.com/project-id'
sources:
  - type: "d0"
    path: "/dev/ttyUSB5"
    uploads:
      1.8.0:
        <<: *remote
        serial: "ABC123"
  - type: "modbus"
    url: "modbus://127.0.0.1:502"
    unit_id: 128
    registers:
      totalWH:
        address: 40302
        register_count: 4
        unit: 'Wh'
  - type: "modbus"
    path: "/dev/ttyUSB0"
    baud: 4800
    unit_id: 128
    registers:
      totalWH:
        type: input
        address: 30073
        register_count: 2
        format: float
        unit: 'kWh'
  - type: "fritz"
    url: "http://192.168.178.1"
    username: "user"
    password: "123456"
    switches:
      refrigerator: "012340000123"
